name: Publish release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - run: npm install
      - name: Setup wasi-sdk cache
        id: wasi-sdk
        uses: actions/cache@v6
        with:
          path: wasi-sdk
          key: wasi-sdk-29.0-${{ runner.os }}
      - if: steps.wasi-sdk.outputs.cache-hit != 'true'
        name: Install wasi-sdk
        uses: bytecodealliance/setup-wasi-sdk-action@77d09f3df1e8da344d8403cf8631af8977938b4c
        with:
          version: "29"
          install-path: wasi-sdk
          add-to-path: false
      - name: Build parser
        run: npm run generate
      - name: Run tests
        run: npm run test
      - name: Build .wasm
        env:
          TREE_SITTER_WASI_SDK_PATH: wasi-sdk
        run: npm run build:wasm
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.PACKAGE_VERSION }}
          artifacts: "*.wasm"
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
          generateReleaseNotes: true
          omitNameDuringUpdate: true
      - uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --allow-dirty
